### ISSUE TITLE
Controls don't work properly anymore

### ISSUE THREAD

**Issue by pizzadude** [flathub/io.github.shiiion.primehack#26]
As of the latest flatpak updates, controls don't work properly anymore. I can't start the game due to click / enter not working. This is on Fedora 38 KDE (wayland).

I tried downgrading to no avail.

Running it in wine for now.

**Comment by pizzadude** [comment]
Update: I use Warehouse ( https://flathub.org/apps/io.github.flattool.Warehouse ) to downgrade the Primehack flatpak to the last commit from 2022 and that fixes it, for now. You can also use the flatpak CLI to downgrade, if you don't want to use Warehouse.

**Comment by napejuice** [comment]
Same thing here, mouse not working. Fedora 39 KDE on Wayland. Commit 07e94c5f880525814387a4aa9cb147a27efd308abcebb2553d31aae0b9422eed works for me. The evdev update broke it..

**Comment by Ethanscharlie** [comment]
Same issue, does the version on the aur work?

**Comment by napejuice** [comment]
> Same issue, does the version on the aur work?

Fails to compile for me at the mgba module. Clearly someone on the dev team and/or the AUR maintainer needs to fix something. :(

**Comment by Ethanscharlie** [comment]
Same issue with the mgba module when compiling directly from the main repo

**Comment by SirMangler** [comment]
Hopefully this will be fixed with the next rebase. There were some changes to fix the steamdeck controls as mentioned in the latest blog post. 

> Clearly someone on the dev team and/or the AUR maintainer needs to fix something. :(

We don't maintain the AUR or have any control over it.

**Comment by pizzadude** [comment]
This isn't an issue for me anymore with latest primehack, on Fedora 40 KDE (Plasma 6).
