### ISSUE TITLE
App wont open until its rebuilt because of ABI changes

### ISSUE THREAD

**Issue by ZacharyVarney** [flathub/io.github.shiiion.primehack#30]
App wont open & reports error 
> dolphin-emu: symbol lookup error: dolphin-emu: undefined symbol: _Zls6QDebugRK11QDockWidget, version Qt_6

Other emulator flatpak's have figured out how to fix the issue by doing a manual rebuild of the applications, here are a few sources

[https://github.com/flathub/org.citra_emu.citra/issues/658](https://github.com/flathub/org.citra_emu.citra/issues/658)
[https://github.com/flathub/net.rpcs3.RPCS3/issues/1632#issuecomment-1975348655](https://github.com/flathub/net.rpcs3.RPCS3/issues/1632#issuecomment-1975348655)

**Comment by SirMangler** [comment]
I have pushed a manual build similarly to these other two. Thanks for including them so I could quickly verify the issue. Will need to see if this is resolved once the new build is pushed in a few hours.

https://buildbot.flathub.org/#/builders/6/builds/105006

**Comment by ZacharyVarney** [comment]
This did the trick for me & it now works just fine, thank you!

**Comment by SirMangler** [comment]
Thanks for letting me know!
